### ISSUE TITLE
Close Channel to finish reading

### ISSUE THREAD

**Issue by shaardie** [lkiesow/go-scan-http#6]
You do not need a `done` channel in `handleResults`. You can simply range over the channel in a for loop which automatically stops if the channel is closed. See this example

```go
package main

import (
	"fmt"
	"sync"
)

func main() {
	var wg sync.WaitGroup
	printer := make(chan int, 64)
	go func() {
		wg.Add(1)
		for i := range printer {
			fmt.Printf("Number: %v\n", i)
		}
		wg.Done()
	}()
	for i := 0; i < 1024; i++ {
		printer <- i
	}
	close(printer)
	wg.Wait()
}
```

**Comment by lkiesow** [comment]
Doesn't this just replace the `done` channel with a wait group?
Is there any advantage of this over a channel?

**Comment by shaardie** [comment]
You are right, but I would still use the `waitGroup`, since it seems like the canonical way to me. After a short search on google, I just found out that `waitGroup` is a little bit faster, but it seems that both cases are in use.

**Comment by lkiesow** [comment]
`done` is done.
